name: pruebaproyecto1
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  auto_size_text: 3.0.0
  flutter_svg: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/pruebaproyecto1/assets/images/homepage.png
    - packages/pruebaproyecto1/assets/images/soccerplayer.png
    - packages/pruebaproyecto1/assets/images/teams.png
    - packages/pruebaproyecto1/assets/images/calendar16.png
    - packages/pruebaproyecto1/assets/images/table.png
    - packages/pruebaproyecto1/assets/images/cerrarsesion.svg
    - packages/pruebaproyecto1/assets/images/c35srcs7brimpbi4n3anzteu6q1.png
    - packages/pruebaproyecto1/assets/images/dacahm53dzcwlh6jbul4n7jsky1.png
    - packages/pruebaproyecto1/assets/images/mesi1.png
    - packages/pruebaproyecto1/assets/images/image2.png
    - packages/pruebaproyecto1/assets/images/maradona1.png
    - packages/pruebaproyecto1/assets/images/pele1.png
    - packages/pruebaproyecto1/assets/images/johancruyff1.png
    - packages/pruebaproyecto1/assets/images/franzbeckenbauer1.png
    - packages/pruebaproyecto1/assets/images/chovas1.png
    - packages/pruebaproyecto1/assets/images/clubamerica1.png
    - packages/pruebaproyecto1/assets/images/ftbolclubatlas1.png
    - packages/pruebaproyecto1/assets/images/i1.png
    - packages/pruebaproyecto1/assets/images/goback.png
    - packages/pruebaproyecto1/assets/images/164813443904971.png
    - packages/pruebaproyecto1/assets/images/descarga1.png
    - packages/pruebaproyecto1/assets/images/maradonamundial86conlacopa1.png
    - packages/pruebaproyecto1/assets/images/descarga11.png
    - packages/pruebaproyecto1/assets/images/descarga21.png
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - packages/pruebaproyecto1/assets/images/10072953297iniciosdeatlasmarco1.png
    - packages/pruebaproyecto1/assets/images/bravos1.png
    - ""
    - packages/pruebaproyecto1/assets/images/gmaillogo.png
    - packages/pruebaproyecto1/assets/images/eye.png
    - packages/pruebaproyecto1/assets/images/logosamplebytailorbrands1.png
    - packages/pruebaproyecto1/assets/images/line1.svg
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n\n
    - ""
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n\n
    - >
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n\n
    - >
      packages/pruebaproyecto1/assets/images/primerplanteldelclubamricaenlaligamexicana1917181.png\n\n\n
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n\n
    - >
      packages/pruebaproyecto1/assets/images/primerplanteldelclubamricaenlaligamexicana1917181.png\n\n
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png\n
    - >
      packages/pruebaproyecto1/assets/images/primerplanteldelclubamricaenlaligamexicana1917181.png\n
    - >
      packages/pruebaproyecto1/assets/images/15051525246758791505153098noticianormal1.png
    - >
      packages/pruebaproyecto1/assets/images/primerplanteldelclubamricaenlaligamexicana1917181.png
